### ISSUE TITLE
感觉很好用，已经在使用了，给点小建议

### ISSUE THREAD

**Issue by Shuimo03** [leedom92/hexo-theme-leedom#2]
我的系统是Windows11, node版本是v16.11.1，但是在根目录下输入npm i hexo-theme-leedom会报错，然后clone项目下来，我放在根目录修改主题为leedom没有用，解决方法是在blog下的theme中更换项目中的所有目录，然后在修改_config.yml

**Comment by leedom92** [comment]
@Shuimo03 你好
1. npm安装方式报错已修复
```sh
npm i hexo-theme-leedom
```

2. 第二种安装方式只需在你的hexo项目根目录执行以下命令：
> 不要忘记在仓库地址后面还要加上`themes/leedom`
```sh
git clone https://github.com/leedom92/hexo-theme-leedom.git themes/leedom
```
然后在项目根目录下的`_config.yml` 文件中，编辑 `theme` 为 `leedom` 即可：
```yml
theme: leedom
```

谢谢你的反馈！
